### PR TITLE
update for JSweet 2.0.1.

### PR DESCRIPTION
**Pull request by schaumb**
I don't want to use another's feather to impress, but this repo need to change the version (thx @tmatz)

### CODE REVIEW

**Comment by renaudpawlak** [comment]
Nice! :D Great job!

**Comment by renaudpawlak** [comment]
@schaumb : could you solve the conflict please :)

**Comment by schaumb** [comment]
Yes, I Will :)

**Comment by schaumb** [comment]
I will wait for the other pull requests, because i don't want to merging manually each time

**Comment by renaudpawlak** [comment]
I gave you the admin privilege on the repo. So you should be able to merge :)
Use with care ;)

**Pull request merged**
